version: '2.2'

services:
  # rabbit: 
  #   image: rabbitmq:3.7-management
  #   ports:
  #    - 5672:5672
  #    - 15672:15672

  # webapp:
  #   build: ./spring-app/.
  #   image: spring-demo
  #   ports:
  #     - 8080:8080
  #   command: 
  #     - web

  # worker:
  #   image: spring-demo
  #   command: 
  #     - poller

  eureka: 
    image: spring-study-eureka
    build: ./eureka/.
    environment: 
      - SERVER_PORT=8761
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
    ports:
      - 8761:8761

  config-server: 
    image: spring-study-config-server
    build: ./config-server/.
    environment: 
      - SERVER_PORT=8080
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
    ports:
      - 8080:8080

  a: 
    image: abc-app
    build: ./abc-app/.
    environment: 
      - SERVER_PORT=8084
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8080
      - SPRING_APPLICATION_NAME=a
      - ABCCLIENT_NAME=b
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
    restart: always
    ports:
      - 8084:8084

  b: 
    image: abc-app
    environment: 
      - SERVER_PORT=8085
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8080
      - SPRING_APPLICATION_NAME=b
      - ABCCLIENT_NAME=c
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
    restart: always
    ports:
      - 8085:8085

  c: 
    image: abc-app
    environment: 
      - SERVER_PORT=8086
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8080
      - SPRING_APPLICATION_NAME=c
      - ABCCLIENT_NAME=a
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
    restart: always
    ports:
      - 8086:8086

  zuul:
    build: ./zuul/.
    image: api-gateway
    environment: 
      - SERVER_PORT=9000
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8080
      - SPRING_APPLICATION_NAME=zuul
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
    restart: always
    ports:
      - 9000:9000

  zipkin:
    image: openzipkin/zipkin
    ports: 
      - 9411:9411