version: '2.2'

services:
  # rabbit: 
  #   image: rabbitmq:3.7-management
  #   ports:
  #    - 5672:5672
  #    - 15672:15672

  # webapp:
  #   build: ./spring-app/.
  #   image: spring-demo
  #   ports:
  #     - 8080:8080
  #   command: 
  #     - web

  # worker:
  #   image: spring-demo
  #   command: 
  #     - poller

  eureka: 
    image: spring-study-eureka
    build: ./eureka/.
    environment: 
      - SERVER_PORT=8761
    ports:
      - 8761:8761

  config-server: 
    image: spring-study-config-server
    build: ./config-server/.
    environment: 
      - SERVER_PORT=8080
    ports:
      - 8080:8080

  abc-app: 
    image: abc-app
    build: ./abc-app/.
    environment: 
      - SERVER_PORT=8084
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8080
    restart: always
    ports:
      - 8084:8084