spring:
  application:
    name: "config-server"
  profiles: 
    active: native
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: file://app/configs
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true