#spring:
#  cloud:
#    stream:
#      default:
#        contentType: application/json
#      bindings:
#        sample-sink:
#          destination: pollerIn-process
#          binder: chat
#      binders:
#        chat:
#          type: rabbit
#          environment:
#            spring.rabbitmq.addresses: amqp://localhost
#

# URL ending with ?format=xml can specify requested media type:
spring.mvc.contentnegotiation.favor-parameter: true

# URL ending with .xml or .json can specify the requested media type:
spring.mvc.contentnegotiation.favor-path-extension: true
spring.mvc.pathmatch.use-suffix-pattern: true


management.endpoints.web.exposure.include: beans,configprops,mappings,env,autoconfig




spring:
  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        chatMessagesOutput:
          destination: chatMessagesInput

  rabbitmq:
    addresses: amqp://127.0.0.1